---
# Global settings for the entire lab infrastructure
ansible_user: "ubuntu" # Default user for initial connection
k3s_version: "v1.35.1+k3s1" # Target K3s version
k8s_kubeconfig: /etc/rancher/k3s/k3s.yaml
timezone: "Europe/London"

# Calico
calico_version: "v3.29.1"
pod_cidr: "10.42.0.0/16"

# MetalLB
metallb_version: "v0.14.9"
metallb_ip_range: "192.168.0.200-192.168.0.210"

# Namespaces
metallb_namespace: "metallb-system"
calico_namespace: "calico-system"

# Gateway API
gateway_api_version: "v1.4.1"
gateway_api_channel: "standard"

# Envoy Gateway
envoy_gateway_version: "v1.7.0"
envoy_gateway_namespace: "envoy-gateway-system"

# Network definition
network_config:
  gateway: "192.168.0.1"
  dns_servers:
    - "8.8.8.8"
    - "1.1.1.1"
  trusted_subnet: "192.168.0.0/24"
  emergency_ip: "192.168.0.50"  # Add a local machine ip

# Node IP definitions
nodes:
  bastion: "192.168.0.105"
  master: "192.168.0.100"
  worker1: "192.168.0.101"
  worker2: "192.168.0.102"
  master_node: "tunga-master"  

# Monitoring configuration
monitoring:
  namespace: "monitoring"
  prometheus_stack_chart: "kube-prometheus-stack"
  prometheus_stack_repo: "https://prometheus-community.github.io/helm-charts"
  release_name: "prometheus"
  grafana_admin_password: "{{ vault_grafana_admin_password }}"
