$ANSIBLE_VAULT;1.1;AES256
65613730626330313130613130643166316663373632643861336630306637653035663237653163
3832396165313561303639653731613534393037363862630a383635373231323063396433306465
32346231373338646461363862373435633366656661346563653539623063343630396431383935
3732623336336633360a363563396262636434396539663561656239633161313961633461396532
30666530313634633635313665613766656135633663663539306565336565633435396133343536
39653661323363343930616664353230303233653262373738343064346634636139623965373866
38326231303865306566636234636233326633313732393131646561373138663435346435393437
35326364353532623638633366646464386438313537353831613563643832393530376434363334
35613563633236366533383232643533373763633833363561653635326163373137343364323637
6662653637633336366166366337616261656336646264623930
